#!/usr/bin/env bash
mkdir -p dist
echo "Transpiling LiveScript"
./node_modules/.bin/lsc -cbp src/ldq.ls > dist/ldq.js
echo "Uglifying ldq.js"
./node_Modules/.bin/uglifyjs dist/ldq.js > dist/ldq.min.js
echo "Done."
