#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "Transpiling src/ldq.ls -> dist/ldq.js ... "
npx lsc -cp src/ldq.ls > dist/ldq.js
echo "Uglifying ldq.js"
npx uglifyjs dist/ldq.js > dist/ldq.min.js
echo "Done."
